name: Run API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          pip install allure-pytest
          mkdir -p allure-report
          npx allure generate allure-results -o allure-report --clean
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
